apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: w6c0uw6r5-python
  janus-idp.io/tekton: w6c0uw6r5-python
  backstage.io/kubernetes-id: w6c0uw6r5-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w6c0uw6r5-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
